name: mini_mcp_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  dart_mcp: ^0.3.2
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
